#!/usr/bin/env bash
# Summarize cycling infrastructure mapped in OSM within print bbox.
# Schema: osm2pgsql -c -G --slim --hstore (planet_osm_line/point/polygon)
# Promoted columns include: highway, route, name, bicycle, foot, surface
# Non-column tags (cycleway, cycleway:left, etc.) live in the `tags` hstore column.
set -euo pipefail
cd "$(dirname "$0")"

{
  echo "# Bike-infrastructure audit (print bbox, OSM data 2026-07-03)"
  echo
  echo "Generated by audit-bike-infra.sh — re-run after editing OSM + re-importing."
  echo

  echo '## Dedicated cycleways (highway=cycleway)'
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT coalesce(name,'(unnamed)') || ' — ' || round(sum(ST_Length(way))::numeric) || 'm'
     FROM planet_osm_line WHERE highway='cycleway'
     GROUP BY name ORDER BY sum(ST_Length(way)) DESC;"
  echo '```'
  echo

  echo '## Streets with cycle lanes/tracks (cycleway* tags)'
  # cycleway, cycleway:left, cycleway:right, cycleway:both live in hstore `tags`
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT DISTINCT coalesce(name,'(unnamed)') || ' [' ||
       concat_ws(',', tags->'cycleway', tags->'cycleway:left',
                      tags->'cycleway:right', tags->'cycleway:both') || ']'
     FROM planet_osm_line
     WHERE tags ?| ARRAY['cycleway','cycleway:left','cycleway:right','cycleway:both']
       AND highway IS NOT NULL
     ORDER BY 1;"
  echo '```'
  echo

  echo '## Named bicycle routes (route=bicycle)'
  # route is a promoted column in the osm2pgsql default style
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT coalesce(name,'(unnamed)') || coalesce(' (' || ref || ')','')
     FROM planet_osm_line WHERE route='bicycle'
     GROUP BY name, ref ORDER BY name;"
  echo '```'
  echo

  echo '## Shared paths — foot+bicycle designated (highway=cycleway/path/track)'
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT highway || ' | foot=' || coalesce(foot,'?') || ' | bicycle=' || coalesce(bicycle,'?') ||
       ' | count=' || count(*)
     FROM planet_osm_line
     WHERE (foot='designated' OR bicycle='designated')
       AND highway IN ('path','footway','cycleway','track')
     GROUP BY highway, foot, bicycle ORDER BY count(*) DESC;"
  echo '```'
  echo

  echo '## Cycling amenities (parking, repair stations, rental)'
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT amenity || ' | count=' || count(*)
     FROM planet_osm_point
     WHERE amenity IN ('bicycle_parking','bicycle_rental','bicycle_repair_station')
     GROUP BY amenity ORDER BY count(*) DESC;"
  echo '```'
  echo

  echo '## Bike shops'
  echo '```'
  docker compose run --rm -T tools psql -d osm -Atc \
    "SELECT coalesce(name,'(unnamed)') FROM planet_osm_point WHERE shop='bicycle'
     UNION
     SELECT coalesce(name,'(unnamed)') FROM planet_osm_polygon WHERE shop='bicycle'
     ORDER BY 1;"
  echo '```'

} > AUDIT.md

echo "AUDIT.md written."
